### ISSUE TITLE
Anchor tags

### ISSUE THREAD

**Issue by SQL-MisterMagoo** [fingers10/BlazorParallax#1]
You might not know , but you can use `target="_top"` on your NavLinks to enable the browser to scroll for you - meaning you can remove all the javascript for `scrollTo` etc.

```
<NavLink class="nav-item nav-link" href="#page-hero" target="_top" Match="NavLinkMatch.All">home</NavLink>
```

**Comment by fingers10** [comment]
will this work for all sections?

**Comment by SQL-MisterMagoo** [comment]
Yes, but there is a downside because some browsers support smooth scrolling - Firefox, some don't. 

To try this, just add the target to your navlinks and remove the JavaScript

**Comment by fingers10** [comment]
Hey I tried this. It works like charm. I'll update the code and add comments. So that the user who needs animation can use JavaScript and who don't need animation can proceed with your suggestion.

Thanks,
Abdul Rahman
